"""Reusable DS/ML experimentation contracts for consumer projects."""

from ds_platform.modeling.capabilities import (
    Classifier,
    Clusterer,
    ConditionedEncoder,
    Embedder,
    PerspectiveComposer,
    Regressor,
    SequenceEncoder,
)
from ds_platform.modeling.encode import EncodingResult, run_encoding
from ds_platform.modeling.evaluate import (
    EvaluationReport,
    accuracy,
    evaluate,
    macro_f1,
    mae,
    rmse,
)
from ds_platform.modeling.features import (
    FeatureTable,
    FeatureView,
    Scalar,
    align_feature_tables,
    extract_column,
    select_columns,
)
from ds_platform.modeling.geometry import knn, novelty_scores, pairwise_distances
from ds_platform.modeling.interventions import (
    InterventionQuery,
    apply_intervention,
    representation_delta,
    rollout,
)
from ds_platform.modeling.pairs import PairTable, align_pairs
from ds_platform.modeling.perspectives import (
    PerspectivePath,
    PerspectiveTable,
    compose_perspectives,
    join_pair_key,
    pairwise_perspective_distances,
    perspectives_for_subject,
    split_pair_key,
    subjects_for_perspective,
    to_representation_table,
)
from ds_platform.modeling.records import (
    PredictionRow,
    prediction_payload_bytes,
    put_evaluation_artifact,
    put_feature_dataset,
    put_index_artifact,
    put_model_artifact,
    put_prediction_artifact,
    representation_payload_bytes,
)
from ds_platform.modeling.representations import (
    RepresentationTable,
    align_representation_tables,
    as_feature_table,
    mean_cosine_similarity,
    representation_mse,
    select_entities,
)
from ds_platform.modeling.run import ExperimentResult, run_experiment
from ds_platform.modeling.sequences import (
    SequenceTable,
    attach_representations,
    events_for_group,
    order_events,
    pool_groups,
)
from ds_platform.modeling.spec import (
    ConditioningSpec,
    DatasetRef,
    EncodingSpec,
    ExperimentSpec,
    FeatureSpec,
    GeometrySpec,
    MetricSpec,
    ModelSpec,
    PerspectiveSpec,
    SequenceSpec,
    SplitSpec,
    TargetSpec,
    experiment_config_hash,
    spec_config_hash,
)
from ds_platform.modeling.split import (
    SplitAssignment,
    apply_group_split,
    apply_split,
    split_entities,
    split_groups,
)

__all__ = [
    "Classifier",
    "Clusterer",
    "ConditionedEncoder",
    "ConditioningSpec",
    "DatasetRef",
    "Embedder",
    "EncodingResult",
    "EncodingSpec",
    "EvaluationReport",
    "ExperimentResult",
    "ExperimentSpec",
    "FeatureSpec",
    "FeatureTable",
    "FeatureView",
    "GeometrySpec",
    "InterventionQuery",
    "MetricSpec",
    "ModelSpec",
    "PairTable",
    "PerspectiveComposer",
    "PerspectivePath",
    "PerspectiveSpec",
    "PerspectiveTable",
    "PredictionRow",
    "Regressor",
    "RepresentationTable",
    "Scalar",
    "SequenceEncoder",
    "SequenceSpec",
    "SequenceTable",
    "SplitAssignment",
    "SplitSpec",
    "TargetSpec",
    "accuracy",
    "align_feature_tables",
    "align_pairs",
    "align_representation_tables",
    "apply_group_split",
    "apply_intervention",
    "apply_split",
    "as_feature_table",
    "attach_representations",
    "compose_perspectives",
    "evaluate",
    "events_for_group",
    "experiment_config_hash",
    "extract_column",
    "join_pair_key",
    "knn",
    "macro_f1",
    "mae",
    "mean_cosine_similarity",
    "novelty_scores",
    "order_events",
    "pairwise_distances",
    "pairwise_perspective_distances",
    "perspectives_for_subject",
    "pool_groups",
    "prediction_payload_bytes",
    "put_evaluation_artifact",
    "put_feature_dataset",
    "put_index_artifact",
    "put_model_artifact",
    "put_prediction_artifact",
    "representation_delta",
    "representation_mse",
    "representation_payload_bytes",
    "rmse",
    "rollout",
    "run_encoding",
    "run_experiment",
    "select_columns",
    "select_entities",
    "spec_config_hash",
    "split_entities",
    "split_groups",
    "split_pair_key",
    "subjects_for_perspective",
    "to_representation_table",
]
